### ISSUE TITLE
Fail to build with Boost 1.71.0

### ISSUE THREAD

**Issue by Cryspia** [GrammaTech/gtirb#31] opened 2019-09-16 18:15 UTC
Build fails in `TestGTIRB.dir/AuxData.test.cpp.o` at `BOOST_STATIC_ASSERT(detail::is_endian_reversible<EndianReversible>::value);`

**Comment by jpc0016** [comment] 2019-09-18 16:34
I also get the same error at [81%] build.  Same object file too.  Would appreciate input from GrammaTech!

**Comment by iconmaster5326** [comment] 2019-09-18 18:46
We've managed to reproduce the issue and we are looking into the cause now. It should be noted that Boost 1.70.0 is tested to work, if you'd like to use that in the meantime. Thanks for reporting the issue!

**Comment by tjohnson-gt** [comment] 2019-09-19 18:18
This issue should be fixed as of d64aefeecaea0ea9e637dcde0ee03dd5c7212c80, showing up in version 0.2.0.

**Closed by tjohnson-gt** 2019-09-19 18:18 UTC
